package graduation.choiharin.domain.entity;

public enum GoogleCategory {
    ALL, ACCOUNTING, AIRPORT, AMUSEMENT_PARK, AQUARIUM, ART_GALLERY, BAKERY, BAR, BEAUTY_SALON,
    BICYCLE_STORE, BOOK_STORE, CAFE, CLOTHING_STORE, CONVENIENCE_STORE, DEPARTMENT_STORE,
    DRUGSTORE, ELECTRONICS_STORE, FLORIST, FURNITURE_STORE, GAS_STATION, GYM, HAIR_CARE, HARDWARE_STORE,
    HOME_GOODS_STORE, JEWELRY_STORE, LAUNDRY, LIQUOR_STORE, MEAL_DELIVERY, MEAL_TAKEAWAY, MOVIE_THEATER,
    MOVING_COMPANY, MUSEUM, PET_STORE, PHARMACY, RESTAURANT, SCHOOL, SHOE_STORE, SHOPPING_MALL, SPA,
    STADIUM, STORE, SUPERMARKET, VETERINARY_CARE, ZOO
}
