spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/data-jpa-h2
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://choiharindatabase.c3soywpqhyzg.ap-northeast-2.rds.amazonaws.com:3306/ChoiharinDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: harin2023!
  jpa:
    hibernate:
      ddl-auto: validate #update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect #로컬 H2 데이터베이스용
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 500

logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
  org.hibernate.type: trace #띄어쓰기 2칸

jwt:
  header: Authorization
#  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: /XHjDqHZhpTq26Jw3mOLCXZtNku8iyXLA90Q/LkQVm6Pt7VZ4/zHXlEz2yICFwF90ILYROEqXKyX64hvdyQ2aA==
  #token 유효 기간 1개월로 설정해둠. 한 달에 한 번씩 로그인하기 번거로우면 access token 도입(복잡하므로 메인 개발 끝난 후)
  #토큰 유효기간이 만료됐으면 자동 로그아웃하고 로그인 페이지로 이동 -> 프론트에서 가능. 백엔드는 토큰 검증만 수행
  token-validity-in-seconds: 2592000